// This file is auto-generated by tauri-specta. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	openLibrary: (path: string) => typedError<LibraryMeta, CommandError>(__TAURI_INVOKE("open_library", { path })),
	startDiscovery: () => typedError<null, CommandError>(__TAURI_INVOKE("start_discovery")),
	cancelDiscovery: () => typedError<null, CommandError>(__TAURI_INVOKE("cancel_discovery")),
	startAnalysis: (reanalyze: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("start_analysis", { reanalyze })),
	cancelAnalysis: () => typedError<null, CommandError>(__TAURI_INVOKE("cancel_analysis")),
	getSamples: () => typedError<SampleRow[], CommandError>(__TAURI_INVOKE("get_samples")),
	getSample: (sampleId: SampleId) => typedError<SampleRow, CommandError>(__TAURI_INVOKE("get_sample", { sampleId })),
	listTagDimensions: () => typedError<TagDimension[], CommandError>(__TAURI_INVOKE("list_tag_dimensions")),
	setUserTag: (sampleId: SampleId, dimension: string, value: string) => typedError<null, CommandError>(__TAURI_INVOKE("set_user_tag", { sampleId, dimension, value })),
	setUserTagBulk: (sampleIds: SampleId[], dimension: string, value: string) => typedError<null, CommandError>(__TAURI_INVOKE("set_user_tag_bulk", { sampleIds, dimension, value })),
	clearUserTag: (sampleId: SampleId, dimension: string) => typedError<null, CommandError>(__TAURI_INVOKE("clear_user_tag", { sampleId, dimension })),
	clearUserTagBulk: (sampleIds: SampleId[], dimension: string) => typedError<null, CommandError>(__TAURI_INVOKE("clear_user_tag_bulk", { sampleIds, dimension })),
	getSamplePlayback: (sampleId: SampleId) => typedError<PlaybackSample, CommandError>(__TAURI_INVOKE("get_sample_playback", { sampleId })),
	getMlModelStatus: () => typedError<MlModelStatus, CommandError>(__TAURI_INVOKE("get_ml_model_status")),
	downloadMlModel: () => typedError<MlModelStatus, CommandError>(__TAURI_INVOKE("download_ml_model")),
};

/* Types */
export type AnalysisStatus = "pending" | "analysing" | "done" | "failed";

export type CommandError = ({ Database: string }) & { Analysis?: never; DiscoveryCancelled?: never; Io?: never; Other?: never } | ({ Io: string }) & { Analysis?: never; Database?: never; DiscoveryCancelled?: never; Other?: never } | "NoLibraryOpen" | ({ Analysis: string }) & { Database?: never; DiscoveryCancelled?: never; Io?: never; Other?: never } | ({ DiscoveryCancelled: {
	count: number,
} }) & { Analysis?: never; Database?: never; Io?: never; Other?: never } | ({ Other: string }) & { Analysis?: never; Database?: never; DiscoveryCancelled?: never; Io?: never };

export type DimensionValueType = "enum" | "multi_enum" | "numeric" | "text";

export type LibraryMeta = {
	root_path: string,
	created_at: number,
	last_discovered_at: number | null,
};

export type MlModelStatus = {
	model_id: string,
	found: boolean,
	path: string,
	missing_files: string[],
	size_bytes: number,
};

export type PlaybackSample = {
	id: number,
	filename: string,
	path: string,
	duration_ms: number | null,
	waveform_data: number[] | null,
	is_loop: boolean,
};

/**
 *  Sample identifier as used in command signatures. Exposed to TypeScript as
 *  a plain `number` while staying `i64` on the Rust side to match the schema.
 */
export type SampleId = number;

export type SampleRow = {
	id: number,
	filename: string,
	relative_path: string,
	format: string | null,
	size_bytes: number | null,
	duration_ms: number | null,
	sample_rate: number | null,
	bit_depth: number | null,
	channels: number | null,
	analysis_status: AnalysisStatus,
	tags: SampleTag[],
	conflicts: TagConflict[],
};

export type SampleTag = {
	dimension: string,
	value: string,
	source: TagSource,
	confidence: number | null,
	is_primary: boolean,
};

export type TagConflict = {
	dimension: string,
	candidates: SampleTag[],
};

export type TagDimension = {
	name: string,
	value_type: DimensionValueType,
	values: string[],
};

export type TagSource = "heuristic" | "metadata" | "model" | "user";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

