// This file is auto-generated by tauri-specta. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	openLibrary: (path: string) => typedError<LibraryMeta, CommandError>(__TAURI_INVOKE("open_library", { path })),
	startDiscovery: () => typedError<null, CommandError>(__TAURI_INVOKE("start_discovery")),
	cancelDiscovery: () => typedError<null, CommandError>(__TAURI_INVOKE("cancel_discovery")),
	startAnalysis: (reanalyze: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("start_analysis", { reanalyze })),
	getSamples: () => typedError<SampleRow[], CommandError>(__TAURI_INVOKE("get_samples")),
	setUserTag: (sampleId: number, dimension: string, value: string) => typedError<null, CommandError>(__TAURI_INVOKE("set_user_tag", { sampleId, dimension, value })),
	clearUserTag: (sampleId: number, dimension: string) => typedError<null, CommandError>(__TAURI_INVOKE("clear_user_tag", { sampleId, dimension })),
};

/* Types */
export type AnalysisStatus = "pending" | "analysing" | "done" | "failed";

export type CommandError = ({ Database: string }) & { Analysis?: never; DiscoveryCancelled?: never; Io?: never; Other?: never } | ({ Io: string }) & { Analysis?: never; Database?: never; DiscoveryCancelled?: never; Other?: never } | "NoLibraryOpen" | ({ Analysis: string }) & { Database?: never; DiscoveryCancelled?: never; Io?: never; Other?: never } | ({ DiscoveryCancelled: {
	count: number,
} }) & { Analysis?: never; Database?: never; Io?: never; Other?: never } | ({ Other: string }) & { Analysis?: never; Database?: never; DiscoveryCancelled?: never; Io?: never };

export type LibraryMeta = {
	root_path: string,
	created_at: number,
	last_discovered_at: number | null,
};

export type SampleRow = {
	id: number,
	filename: string,
	relative_path: string,
	format: string | null,
	size_bytes: number | null,
	analysis_status: AnalysisStatus,
	tags: SampleTag[],
};

export type SampleTag = {
	dimension: string,
	value: string,
	source: TagSource,
	confidence: number | null,
};

export type TagSource = "heuristic" | "metadata" | "model" | "user";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

