pub mod analysis;
pub mod commands;
pub mod db;
pub mod error;
pub mod library;
pub mod models;
mod state;
pub mod tags;

use state::AppState;
use std::path::PathBuf;

fn bindings_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/lib/bindings/bindings.ts")
}

fn specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new().commands(tauri_specta::collect_commands![
        commands::open_library,
        commands::start_discovery,
        commands::cancel_discovery,
        commands::start_analysis,
        commands::cancel_analysis,
        commands::get_samples,
        commands::get_sample,
        commands::list_tag_dimensions,
        commands::set_user_tag,
        commands::set_user_tag_bulk,
        commands::clear_user_tag,
        commands::clear_user_tag_bulk,
        commands::get_sample_playback,
        commands::get_ml_model_status,
        commands::download_ml_model,
    ])
}

pub fn export_bindings() {
    specta_builder()
        .export(
            specta_typescript::Typescript::default()
                .header("// This file is auto-generated by tauri-specta. Do not edit.\n"),
            bindings_path(),
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = specta_builder();

    #[cfg(debug_assertions)]
    export_bindings();

    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .manage(AppState::default())
        .invoke_handler(builder.invoke_handler())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
